```{r}
library(tidyverse)
library(Interventions)
library(phyloseq)

library(glmnet)
library(pROC)

library(ggplot2)
library(ggembl)
library(ggpubr)
library(ggrepel)

set.seed(123)
```

# Merge Taxonomy tables

```{r}
shotgun_studies <- read.csv("../data/query/Query_Final.csv") %>% 
  filter(Notes == "Shotgun") %>% 
  mutate(Study = gsub("-", "", First.Author)) %>% 
  pull(Study)

`16S_studies` <- read.csv("../data/query/Query_Final.csv") %>% 
  filter(Notes == "16s") %>% 
  mutate(Study = gsub("-", "", First.Author)) %>% 
  pull(Study)

Phyloseq_list <- readRDS("../data/preprocessing/Phyloseq.RDS")

tax_list_shotgun <- lapply(Phyloseq_list[shotgun_studies], function(df) as.data.frame(otu_table(df)) %>% rownames_to_column("Bacteria") %>% mutate(Bacteria = clearNames(Bacteria)))
tax_list_16S <- lapply(Phyloseq_list[`16S_studies`], function(df) as.data.frame(otu_table(df)) %>% rownames_to_column("Bacteria") %>% mutate(Bacteria = gsub(".*\\|g__", "", Bacteria)))

tax_shotgun <- Reduce(function(df1, df2) merge(df1, df2, by = "Bacteria", all = T), tax_list_shotgun)
rownames(tax_shotgun) <- tax_shotgun$Bacteria
tax_shotgun <- tax_shotgun[, -1]
tax_shotgun[is.na(tax_shotgun)] <- 0

tax_16S <- Reduce(function(df1, df2) merge(df1, df2, by = "Bacteria", all = T), tax_list_16S)
rownames(tax_16S) <- tax_16S$Bacteria
tax_16S <- tax_16S[, -1]
```


```{r}
metadata_list <- readRDS("../data/preprocessing/Metadata.RDS")
for (study_name in names(metadata_list)) {metadata_list[[study_name]]$StudyName <- study_name}
metadata <- bind_rows(metadata_list) %>% select(-X)

tolerance <- 0.25
```


# Compute FC for Bifidobacterium

# LASSO Model

## 16S

```{r}
bifido_abundances_16S <- tax_16S %>% 
  filter(rownames(.) == "Bifidobacterium") %>% 
  t(.) %>% as.data.frame(.) %>% 
  rownames_to_column("Run") %>% 
  merge(metadata %>% select(Run, Individual, Timepoint, StudyName)) %>% 
  mutate(Individual = str_c(StudyName, Individual, sep = "_"))

bifido_fc_16S <- bifido_abundances_16S %>% 
  group_by(Individual) %>% 
  arrange(Timepoint) %>% 
  summarize(fc = Bifidobacterium[1]/Bifidobacterium[2]) %>% 
  ungroup() %>% 
  filter(!is.na(fc)) %>% 
  mutate(Change = case_when(fc >= 1+tolerance ~ "Enriched",
                            fc <= 1-tolerance ~ "Depleted",
                            .default = "No Change"))

response_16S_df <- metadata %>% 
  mutate(Individual = str_c(StudyName, Individual, sep = "_")) %>% 
  merge(bifido_fc_16S %>% select(-fc)) %>% 
  filter(Timepoint == "Before" & Change != "No Change") %>% 
  group_by(Individual) %>% filter(n() == 1) 
response_16S <- response_16S_df$Change
names(response_16S) <- response_16S_df$Run
response_16S <- response_16S[order(names(response_16S))]

tax_16S <- as.data.frame(t(tax_16S))
tax_16S_filt <- tax_16S[names(response_16S),]
tax_16S_filt_mat <- scale(as.matrix(tax_16S_filt))
class(tax_16S_filt_mat) <- "numeric"
tax_16S_filt_mat[is.na(tax_16S_filt_mat)] <- 0
```

```{r}
fit_16S <- cv.glmnet(tax_16S_filt_mat, response_16S,
                     family = "binomial", alpha = 1)

coef_min_16S <- coef(fit_16S, s = "lambda.min")
informative_genera_16S <- rownames(coef_min_16S)[which(coef_min_16S != 0)][-1] %>% as.data.frame() %>% rename("Genera" = 1)
informative_genera_16S$Coefficient <- coef_min_16S[which(coef_min_16S != 0)][-1]

# AUROC
predict_16S <- predict(fit_16S, tax_16S_filt_mat, s = "lambda.min", type = "response")

roc_obj_16S <- roc(response_16S, as.numeric(predict_16S))
auc_value_16S <- auc(roc_obj_16S)
ci_16S <- ci.auc(roc_obj_16S)

# PLOT
roc_df_16S<- data.frame(
  tpr = roc_obj_16S$sensitivities,
  fpr = 1 - roc_obj_16S$specificities
)

ggplot(roc_df_16S, aes(x = fpr, y = tpr)) +
  geom_step(color = "#1c61b6", linewidth = 0.5) +
  geom_smooth(method = "loess", se = FALSE, span = 0.25, color = "#1c61b6", linewidth = 1.2) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "gray") +
  annotate("text", label = paste0("AUC = ", round(auc_value_16S, 2), " (", round(ci_16S[1], 3), "–", round(ci_16S[3], 3), ")"),
           x = 0.70, y = 0.05) +
  ggtitle("ROC Curve - 16S Data") +
  xlab("False Positive Rate") +
  ylab("True Positive Rate") +
  theme_publication() +
  theme(title = element_text(size = 16),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 14)) +
  coord_equal()
ggsave("../figures/bifido/AUROC_16S.pdf")
```

## Shotgun

```{r}
bifido_abundances_shotgun <- tax_shotgun %>% filter(grepl("Bifido", rownames(.))) %>% colSums() %>% 
  as.data.frame() %>% rownames_to_column("Run") %>% rename("Abundance" = ".") %>% 
  merge(metadata %>% select(Run, Individual, Timepoint, StudyName)) %>% 
  mutate(Individual = str_c(StudyName, Individual, sep = "_"))

bifido_fc_shotgun <- bifido_abundances_shotgun %>% 
  group_by(Individual) %>% 
  arrange(Timepoint) %>% 
  summarize(fc = Abundance[1]/Abundance[2]) %>% 
  ungroup() %>% 
  mutate(Change = case_when(fc >= 1+tolerance ~ "Enriched",
                            fc <= 1-tolerance ~ "Depleted",
                            .default = "No Change"))

response_shotgun_df <- metadata %>% 
  mutate(Individual = str_c(StudyName, Individual, sep = "_")) %>% 
  merge(bifido_fc_shotgun %>% select(-fc)) %>% 
  filter(Timepoint == "Before" & Change != "No Change") %>% 
  group_by(Individual) %>% filter(n() == 1) 
response_shotgun <- response_shotgun_df$Change
names(response_shotgun) <- response_shotgun_df$Run
response_shotgun <- response_shotgun[order(names(response_shotgun))]

tax_shotgun <- as.data.frame(t(tax_shotgun))
tax_shotgun_filt <- tax_shotgun[names(response_shotgun),]
tax_shotgun_filt_mat <- scale(as.matrix(tax_shotgun_filt))
class(tax_shotgun_filt_mat) <- "numeric"
tax_shotgun_filt_mat[is.na(tax_shotgun_filt_mat)] <- 0
```

```{r}
fit_shotgun <- cv.glmnet(tax_shotgun_filt_mat, response_shotgun,
                     family = "binomial", alpha = 1)

coef_min_shotgun <- coef(fit_shotgun, s = "lambda.min")
informative_genera_shotgun <- rownames(coef_min_shotgun)[which(coef_min_shotgun != 0)][-1] %>% as.data.frame() %>% rename("Specie" = 1)
informative_genera_shotgun$Coefficient <- coef_min_shotgun[which(coef_min_shotgun != 0)][-1]

# AUROC
predict_shotgun <- predict(fit_shotgun, tax_shotgun_filt_mat, s = "lambda.min", type = "response")

roc_obj_shotgun <- roc(response_shotgun, as.numeric(predict_shotgun))
auc_value_shotgun <- auc(roc_obj_shotgun)
ci_shotgun <- ci.auc(auc_value_shotgun)

# PLOT
roc_df_shotgun <- data.frame(
  tpr = roc_obj_shotgun$sensitivities,
  fpr = 1 - roc_obj_shotgun$specificities
)

ggplot(roc_df_shotgun, aes(x = fpr, y = tpr)) +
  geom_step(color = "#1c61b6", linewidth = 0.5) +
  geom_smooth(method = "loess", se = FALSE, span = 0.25, color = "#1c61b6", linewidth = 1.2) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "gray") +
  annotate("text", label = paste0("AUC = ", round(auc_value_shotgun, 2), " (", round(ci_shotgun[1], 3), "–", round(ci_shotgun[3], 3), ")"),
           x = 0.70, y = 0.05) +
  ggtitle("ROC Curve - Shotgun Data") +
  xlab("False Positive Rate") +
  ylab("True Positive Rate") +
  theme_publication() +
  theme(title = element_text(size = 16),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 14)) +
  coord_equal()
ggsave("../figures/bifido/AUROC_Shotgun.pdf")
```

# Coefficients + Abundances

```{r}
species_abundaces_coefficient <- readRDS("../Preprocessing/Data/Associations_Species_Combined.rds") %>% 
  rownames_to_column("Specie") %>% 
  mutate(Specie = clearNames(Specie)) %>% 
  select(Specie, fc, p.adj) %>% 
  merge(informative_genera_shotgun) %>% 
  mutate(Change = case_when(fc > 0 & Coefficient > 0 ~ "UP",
                            fc < 0 & Coefficient < 0 ~ "DW",
                            .default = "NA"))
  

ggplot(species_abundaces_coefficient, aes(x = fc, y = Coefficient, color = Change)) +
  geom_point() + 
  geom_text_repel(aes(label = Specie), size = 4) +
  scale_color_manual(values = c("UP" = "red", "DW" = "blue", "NA" = "grey70")) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  theme_publication() +
  theme(legend.position = "none",
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 14),
        aspect.ratio = 1) 
ggsave("../figures/bifido/Coefficients Shotgun.pdf")


genera_abundaces_coefficient <- readRDS("../Preprocessing/Data/Associations_Genus_Combined.rds") %>% 
  rownames_to_column("Genera") %>% 
  select(Genera, fc, p.adj) %>% 
  merge(informative_genera_16S) %>% 
  mutate(Change = case_when(fc > 0 & Coefficient > 0 ~ "UP",
                            fc < 0 & Coefficient < 0 ~ "DW",
                            .default = "NA"))
  

ggplot(genera_abundaces_coefficient, aes(x = fc, y = Coefficient, color = Change)) +
  geom_point() + 
  geom_text_repel(aes(label = Genera), size = 4) +
  scale_color_manual(values = c("UP" = "red", "DW" = "blue", "NA" = "grey70")) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  theme_publication() +
  theme(legend.position = "none",
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 14),
        aspect.ratio = 1) 
ggsave("../figures/bifido/Coefficients 16S.pdf")
```


